language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      before_install:
        - brew tap caskroom/cask
        - brew cask install powershell
  fast_finish: true

script:
  - pwsh -c 'Install-Module -Name Pester -Force -SkipPublisherCheck'
  - pwsh -c 'Invoke-Pester -EnableExit'
